/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as QuizExamIdRouteImport } from './routes/quiz.$examId'
import { Route as FeedbackFormIdRouteImport } from './routes/feedback.$formId'
import { Route as AdminWorkshopRouteImport } from './routes/admin.workshop'
import { Route as AdminWebsiteSettingsRouteImport } from './routes/admin.website-settings'
import { Route as AdminSpeakersRouteImport } from './routes/admin.speakers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminPaymentSettingsRouteImport } from './routes/admin.payment-settings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminQuizResponsesRouteImport } from './routes/admin.quiz.responses'
import { Route as AdminQuizQuestionsRouteImport } from './routes/admin.quiz.questions'
import { Route as AdminFeedbackResponsesRouteImport } from './routes/admin.feedback.responses'
import { Route as AdminFeedbackQuestionsRouteImport } from './routes/admin.feedback.questions'
import { Route as AdminFeedbackViewFormIdRouteImport } from './routes/admin.feedback.view.$formId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register/success',
  path: '/register/success',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizExamIdRoute = QuizExamIdRouteImport.update({
  id: '/quiz/$examId',
  path: '/quiz/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackFormIdRoute = FeedbackFormIdRouteImport.update({
  id: '/feedback/$formId',
  path: '/feedback/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkshopRoute = AdminWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSettingsRoute = AdminWebsiteSettingsRouteImport.update({
  id: '/website-settings',
  path: '/website-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentSettingsRoute = AdminPaymentSettingsRouteImport.update({
  id: '/payment-settings',
  path: '/payment-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizResponsesRoute = AdminQuizResponsesRouteImport.update({
  id: '/quiz/responses',
  path: '/quiz/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizQuestionsRoute = AdminQuizQuestionsRouteImport.update({
  id: '/quiz/questions',
  path: '/quiz/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackResponsesRoute = AdminFeedbackResponsesRouteImport.update({
  id: '/feedback/responses',
  path: '/feedback/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackQuestionsRoute = AdminFeedbackQuestionsRouteImport.update({
  id: '/feedback/questions',
  path: '/feedback/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackViewFormIdRoute = AdminFeedbackViewFormIdRouteImport.update({
  id: '/feedback/view/$formId',
  path: '/feedback/view/$formId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/feedback/$formId': typeof FeedbackFormIdRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/feedback/questions': typeof AdminFeedbackQuestionsRoute
  '/admin/feedback/responses': typeof AdminFeedbackResponsesRoute
  '/admin/quiz/questions': typeof AdminQuizQuestionsRoute
  '/admin/quiz/responses': typeof AdminQuizResponsesRoute
  '/admin/feedback/view/$formId': typeof AdminFeedbackViewFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/feedback/$formId': typeof FeedbackFormIdRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/feedback/questions': typeof AdminFeedbackQuestionsRoute
  '/admin/feedback/responses': typeof AdminFeedbackResponsesRoute
  '/admin/quiz/questions': typeof AdminQuizQuestionsRoute
  '/admin/quiz/responses': typeof AdminQuizResponsesRoute
  '/admin/feedback/view/$formId': typeof AdminFeedbackViewFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/website-settings': typeof AdminWebsiteSettingsRoute
  '/admin/workshop': typeof AdminWorkshopRoute
  '/feedback/$formId': typeof FeedbackFormIdRoute
  '/quiz/$examId': typeof QuizExamIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/feedback/questions': typeof AdminFeedbackQuestionsRoute
  '/admin/feedback/responses': typeof AdminFeedbackResponsesRoute
  '/admin/quiz/questions': typeof AdminQuizQuestionsRoute
  '/admin/quiz/responses': typeof AdminQuizResponsesRoute
  '/admin/feedback/view/$formId': typeof AdminFeedbackViewFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/analytics'
    | '/admin/payment-settings'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/website-settings'
    | '/admin/workshop'
    | '/feedback/$formId'
    | '/quiz/$examId'
    | '/register/success'
    | '/admin/'
    | '/register/'
    | '/admin/feedback/questions'
    | '/admin/feedback/responses'
    | '/admin/quiz/questions'
    | '/admin/quiz/responses'
    | '/admin/feedback/view/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/payment-settings'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/website-settings'
    | '/admin/workshop'
    | '/feedback/$formId'
    | '/quiz/$examId'
    | '/register/success'
    | '/admin'
    | '/register'
    | '/admin/feedback/questions'
    | '/admin/feedback/responses'
    | '/admin/quiz/questions'
    | '/admin/quiz/responses'
    | '/admin/feedback/view/$formId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/analytics'
    | '/admin/payment-settings'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/website-settings'
    | '/admin/workshop'
    | '/feedback/$formId'
    | '/quiz/$examId'
    | '/register/success'
    | '/admin/'
    | '/register/'
    | '/admin/feedback/questions'
    | '/admin/feedback/responses'
    | '/admin/quiz/questions'
    | '/admin/quiz/responses'
    | '/admin/feedback/view/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeedbackFormIdRoute: typeof FeedbackFormIdRoute
  QuizExamIdRoute: typeof QuizExamIdRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/register/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$examId': {
      id: '/quiz/$examId'
      path: '/quiz/$examId'
      fullPath: '/quiz/$examId'
      preLoaderRoute: typeof QuizExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$formId': {
      id: '/feedback/$formId'
      path: '/feedback/$formId'
      fullPath: '/feedback/$formId'
      preLoaderRoute: typeof FeedbackFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshop': {
      id: '/admin/workshop'
      path: '/workshop'
      fullPath: '/admin/workshop'
      preLoaderRoute: typeof AdminWorkshopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website-settings': {
      id: '/admin/website-settings'
      path: '/website-settings'
      fullPath: '/admin/website-settings'
      preLoaderRoute: typeof AdminWebsiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-settings': {
      id: '/admin/payment-settings'
      path: '/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AdminPaymentSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz/responses': {
      id: '/admin/quiz/responses'
      path: '/quiz/responses'
      fullPath: '/admin/quiz/responses'
      preLoaderRoute: typeof AdminQuizResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz/questions': {
      id: '/admin/quiz/questions'
      path: '/quiz/questions'
      fullPath: '/admin/quiz/questions'
      preLoaderRoute: typeof AdminQuizQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback/responses': {
      id: '/admin/feedback/responses'
      path: '/feedback/responses'
      fullPath: '/admin/feedback/responses'
      preLoaderRoute: typeof AdminFeedbackResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback/questions': {
      id: '/admin/feedback/questions'
      path: '/feedback/questions'
      fullPath: '/admin/feedback/questions'
      preLoaderRoute: typeof AdminFeedbackQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback/view/$formId': {
      id: '/admin/feedback/view/$formId'
      path: '/feedback/view/$formId'
      fullPath: '/admin/feedback/view/$formId'
      preLoaderRoute: typeof AdminFeedbackViewFormIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminPaymentSettingsRoute: typeof AdminPaymentSettingsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminWebsiteSettingsRoute: typeof AdminWebsiteSettingsRoute
  AdminWorkshopRoute: typeof AdminWorkshopRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFeedbackQuestionsRoute: typeof AdminFeedbackQuestionsRoute
  AdminFeedbackResponsesRoute: typeof AdminFeedbackResponsesRoute
  AdminQuizQuestionsRoute: typeof AdminQuizQuestionsRoute
  AdminQuizResponsesRoute: typeof AdminQuizResponsesRoute
  AdminFeedbackViewFormIdRoute: typeof AdminFeedbackViewFormIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminPaymentSettingsRoute: AdminPaymentSettingsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminWebsiteSettingsRoute: AdminWebsiteSettingsRoute,
  AdminWorkshopRoute: AdminWorkshopRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFeedbackQuestionsRoute: AdminFeedbackQuestionsRoute,
  AdminFeedbackResponsesRoute: AdminFeedbackResponsesRoute,
  AdminQuizQuestionsRoute: AdminQuizQuestionsRoute,
  AdminQuizResponsesRoute: AdminQuizResponsesRoute,
  AdminFeedbackViewFormIdRoute: AdminFeedbackViewFormIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FeedbackFormIdRoute: FeedbackFormIdRoute,
  QuizExamIdRoute: QuizExamIdRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
